version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/
    overwrite: yes
permissions:
  - object: /home/ubuntu/
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: /script.sh
      timeout: 900
      runas: root
